### ISSUE TITLE
Unable to provision CDE VC

### ISSUE THREAD

**Issue by nmarian85** [cloudera-labs/cloudera.cloud#60]
Hello there,

Same error when trying to provision a CDE Virtual Cluster as we had when provisioning the CDP environment:

```bash
- name: "Install {{ cde_vc_name }} CDE virtual cluster"
  cloudera.cloud.de_virtual_cluster:
    name: "{{ cde_vc_name }}"
    cluster_name: "{{ cde_cluster_name }}"
    env: "{{ env_name }}"
    chart_value_overrides: "{{ cde_vc['chart_value_overrides'] }}"
    cpu_requests: "{{ cde_vc['cpu_requests'] }}"
    memory_requests: "{{ cde_vc['memory_requests'] }}"
    acl_users: "{{ cde_vc['acl_users'] }}"
    runtime_spot_component: "{{ cde_vc['runtime_spot_component'] }}"
    spark_version: "{{ cde_vc['spark_version'] }}"



TASK [cde_vc : Install CDE virtual cluster] **************
Friday 29 April 2022  19:39:56 +0000 (0:00:00.080)       0:00:04.408 ********** 
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error": "{'base_error': ClientError('An error occurred: An internal error has occurred. Retry your request, but if the problem persists, contact us with details by posting a message on the Cloudera Community forums. (Status Code: 500; Error Code: UNKNOWN; Service: de; Operation: createVc; Request ID: f5f4369f-e073-4814-be92-da32ed62dd39;)'), 'ext_traceback': ['  File \"/root/.ansible/tmp/ansible-tmp-1651261196.8319285-54-1595965574515/AnsiballZ_de_virtual_cluster.py\", line 107, in <module>\\n    _ansiballz_main()\\n', '  File \"/root/.ansible/tmp/ansible-tmp-1651261196.8319285-54-1595965574515/AnsiballZ_de_virtual_cluster.py\", line 99, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n', '  File \"/root/.ansible/tmp/ansible-tmp-1651261196.8319285-54-1595965574515/AnsiballZ_de_virtual_cluster.py\", line [47](https://gitlab.sofa.dev/ddp/devo/cdp-mgmt/-/jobs/1208367#L47), in invoke_module\\n    runpy.run_module(mod_name=\\'ansible_collections.cloudera.cloud.plugins.modules.de_virtual_cluster\\', init_globals=dict(_module_fqn=\\'ansible_collections.cloudera.cloud.plugins.modules.de_virtual_cluster\\', _modlib_path=modlib_path),\\n', '  File \"/usr/lib64/python3.9/runpy.py\", line 210, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n', '  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\\n    _run_code(code, mod_globals, init_globals,\\n', '  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\\n    exec(code, run_globals)\\n', '  File \"/tmp/ansible_cloudera.cloud.de_virtual_cluster_payload_9twtapqd/ansible_cloudera.cloud.de_virtual_cluster_payload.zip/ansible_collections/cloudera/cloud/plugins/modules/de_virtual_cluster.py\", line 430, in <module>\\n', '  File \"/tmp/ansible_cloudera.cloud.de_virtual_cluster_payload_9twtapqd/ansible_cloudera.cloud.de_virtual_cluster_payload.zip/ansible_collections/cloudera/cloud/plugins/modules/de_virtual_cluster.py\", line 420, in main\\n', '  File \"/tmp/ansible_cloudera.cloud.de_virtual_cluster_payload_9twtapqd/ansible_cloudera.cloud.de_virtual_cluster_payload.zip/ansible_collections/cloudera/cloud/plugins/modules/de_virtual_cluster.py\", line 284, in __init__\\n', '  File \"/tmp/ansible_cloudera.cloud.de_virtual_cluster_payload_9twtapqd/ansible_cloudera.cloud.de_virtual_cluster_payload.zip/ansible_collections/cloudera/cloud/plugins/module_utils/cdp_common.py\", line 42, in _impl\\n    result = f(self, *args, **kwargs)\\n', '  File \"/tmp/ansible_cloudera.cloud.de_virtual_cluster_payload_9twtapqd/ansible_cloudera.cloud.de_virtual_cluster_payload.zip/ansible_collections/cloudera/cloud/plugins/modules/de_virtual_cluster.py\", line 349, in process\\n', '  File \"/tmp/ansible_cloudera.cloud.de_virtual_cluster_payload_9twtapqd/ansible_cloudera.cloud.de_virtual_cluster_payload.zip/ansible_collections/cloudera/cloud/plugins/modules/de_virtual_cluster.py\", line 358, in _create_vc\\n', '  File \"/root/.local/lib/python3.9/site-packages/cdpy/de.py\", line 35, in create_vc\\n    return self.sdk.call(\\n', '  File \"/root/.local/lib/python3.9/site-packages/cdpy/common.py\", line 594, in call\\n    parsed_err = CdpError(err)\\n'], 'error_code': 'UNKNOWN', 'violations': 'An internal error has occurred. Retry your request, but if the problem persists, contact us with details by posting a message on the Cloudera Community forums.', 'message': 'Client request error', 'status_code': '500', 'rc': 1, 'service': 'de', 'operation': 'createVc', 'request_id': 'f5f4369f-e073-[48](https://gitlab.sofa.dev/ddp/devo/cdp-mgmt/-/jobs/1208367#L48)14-be92-da32ed62dd39'}",
    "violations": "An internal error has occurred. Retry your request, but if the problem persists, contact us with details by posting a message on the Cloudera Community forums."
}
MSG:
Client request error
```

**Comment by nmarian85** [comment]
There is also some inconsistency here in the doc https://cloudera-labs.github.io/cloudera.cloud/de_virtual_cluster.html because the list of params specifies cluster_id as required but then in the example cluster_name is being used. Did a bit of testing and kept only the cluster_id and I get an error that I did not specify cluster_name parameter.

**Comment by Chaffelson** [comment]
Yeah looking at the code the provided documentation is wrong.
We get you to submit the name for the vw, and the name for the underlying cluster, then the code derives the necessary IDs from the deployment.
It would probably be better if we allowed you to provide either cluster_id or cluster_name, and handled it in the module.

That said, it should therefore work with name and cluster_name, unless there is another problem.

**Comment by Chaffelson** [comment]
Reproduced the error, looks like there's a change in the API somewhere - will investigate

```
ClientError('An error occurred: An internal error has occurred. Retry your request, but if the problem persists, contact us with details by posting a message on the Cloudera Community forums. (Status Code: 500; Error Code: UNKNOWN; Service: de; Operation: createVc; Request ID: dcff3b91-8561-4a2f-9771-33325ef3f1b2;)
```

**Comment by nmarian85** [comment]
Many thanks for picking up this one so quickly. You've probably already seen that there is a similar (but unrelated) issue when provisioning a CDP environment ( #58 ) and @wmudge was super helpful and has offered a workaround. 
We recycle the CDP environments (+CDW, CDE, CML) quite often since our upgrade concept is that we never do in place upgrades, but do a "blue-green" deployment by building a new env and then pointing our users to that. 
Unfortunately this sort of changes hit us pretty bad as we were trying to provision the new production environment and our pipeline relies on this Ansible Collection.

**Comment by Chaffelson** [comment]
Understood. For the Env one it looks to be a parameter that was optional and is now mandatory, so it's an easy workaround to simply supply it. For this one, it looks to be something within the CDE API for virtual clusters - I've referred it to the owning team as a trouble ticket, but if you can either raise a support ticket or contact me on dchaffey@cloudera.com we'll get you attached to a support ticket and track it formally for your company

**Comment by nmarian85** [comment]
We have our Cloudera RSA coming in tomorrow so we can raise it with him. Hopefully he can add it to your internal JIRA. 
Many thanks again.

**Comment by wmudge** [comment]
I tested the `cloudera.cloud.de_virtual_cluster` module, but was not able to reproduce your error.

```yaml
- name: "Testing cloudera.cloud #60"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    env_name: example-env
    cde_cluster_name: example-cluster
    cde_vc_name: example-vc
    cde_vc:
      chart_value_overrides: "{{ omit }}"
      cpu_requests: "{{ omit }}"
      memory_requests: "{{ omit }}"
      acl_users: "{{ omit }}"
      runtime_spot_component: "{{ omit }}"
      spark_version: "{{ omit }}"
  tasks:
    - name: "Install {{ cde_vc_name }} CDE virtual cluster"
      cloudera.cloud.de_virtual_cluster:
        name: "{{ cde_vc_name }}"
        cluster_name: "{{ cde_cluster_name }}"
        env: "{{ env_name }}"
        chart_value_overrides: "{{ cde_vc['chart_value_overrides'] }}"
        cpu_requests: "{{ cde_vc['cpu_requests'] }}"
        memory_requests: "{{ cde_vc['memory_requests'] }}"
        acl_users: "{{ cde_vc['acl_users'] }}"
        runtime_spot_component: "{{ cde_vc['runtime_spot_component'] }}"
        spark_version: "{{ cde_vc['spark_version'] }}"
```

Please reopen if you are still encountering problems with this module! Thanks!
